#!/bin/sh

test -f configure || autoconf
odin pkg/odin/inc/{Nod,Tok,OC_Nod}Typ_.h
odin pkg/{odin/ipcgen,dg,tregrm}/inc/{Nod,Tok}Typ_.h
for x in dg odin odin/ipcgen tregrm; do
  test -f pkg/$x/inc/Func.hh || touch pkg/$x/inc/Func.hh
done
test -f pkg/tregrm/tregrm-yacc.c.dflt || touch pkg/tregrm/tregrm-yacc.c.dflt
odin pkg/tregrm/tregrm-yacc.c && cp -f pkg/tregrm/tregrm-yacc.c{,.dflt}

test "x$1" = "x-m" || exit 0

# stuff to do for make builds
test -f pkg/odin/inc/config.hh || ./.configure
odin pkg/odin/boot/%boot.sm:list
odin pkg/{dg,odin,odin/ipcgen,tregrm}/inc/Func.hh
odin pkg/odin/inc/odin_builtin.lua.h

